services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    networks: 
      - app-network
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-network
    container_name: api-flask

volumes:
  mysql_data:
networks:
  app-network:
